package com.example.modelo;

import java.util.ArrayList;
import java.util.List;

public class ListaRestaurantes {
    private ArrayList<Restaurante> listaRestaurantes = new ArrayList<>();

    public ArrayList<Restaurante> getListaRestaurantes() {
        return listaRestaurantes;
    }
    public void inicializarRestaurantes(){
        Comida nuggets = new Comida("Nuggets de pollo", "/imagenes/comida/comidaBk/nuggets.jpg",5.00,"¡Prueba nuestros Nugget de Pollo Premium! Trocitos jugosos de pechuga de pollo empanizados y crujientes por fuera, tiernos por dentro. El acompañamiento perfecto para cualquier ocasión: ya sea solo, con tus salsas favoritas o como complemento en tu comida. ¡Ordénalos ahora y disfruta de su sabor irresistiblemente sabroso!");

        Comida bocadillos = new Comida("Bocaditos pollo", "/imagenes/comida/comidaSub/bocadillos.jpg",3.50,"¡Disfruta de nuestros Bocadillos Gourmet! Delicadas rebanadas de pan artesanal rellenas con finas lonchas de jamón serrano, queso brie derretido, tomate fresco y un toque de nuestra exclusiva salsa de higos. Una combinación exquisita de sabores en cada bocado. ¡Ordénalos ahora y deleita tu paladar con esta experiencia gourmet!");
        Comida hamburguesa = new Comida("Hamburguesa con queso", "/imagenes/comida/comidaBk/hamburguesa.jpg",10.0,"¡Descubre nuestra Hamburguesa Tex-Mex! Carne sazonada, queso pepper jack, guacamole fresco, aros de cebolla crujientes y salsa picante, todo en un panecillo de maíz tostado. Una experiencia de sabores del suroeste en cada bocado. ¡Pídela ahora y déjate llevar por su autenticidad!");
        Comida kebab = new Comida("Kebab con carne y pollo", "/imagenes/comida/comidaKebab/kebab.jpg",6.50,"¡Descubre nuestro Kebab de Autor! Deliciosas tiras de carne marinada a la perfección, asadas lentamente con especias tradicionales, servidas en un suave pan de pita junto con crujientes verduras frescas y nuestra exótica salsa de yogurt. Una explosión de sabores auténticos en cada bocado. ¡Ordénalo ahora y déjate llevar por este festín de sabores!");
        Comida patatasFritas = new Comida("Patatas fritas", "/imagenes/comida/comidaMac/patatasFritas.png",3.50,"¡Nuestras Patatas Fritas Crispy! Cortadas en tiras finas y fritas a la perfección para lograr ese crujido irresistible por fuera y su interior suave. Ideales como acompañamiento o como un tentempié delicioso en cualquier momento. ¡Ordénalas ahora y disfruta de este clásico irresistible que nunca pasa de moda!");
        Comida taco = new Comida("Taco con tomate", "/imagenes/comida/comidaTaco/taco.jpg",9.50,"¡Disfruta de nuestro Taco Fresco con Tomate! Una deliciosa combinación de sabores mexicanos en una tortilla de maíz rellena de carne sazonada, cebolla picada, cilantro fresco y rodajas jugosas de tomate. El toque perfecto de frescura en cada bocado. ¡Ordénalo ahora y saborea esta explosión de sabores auténticos!");
        Comida pollo = new Comida("Pollo frito con salsa BBQ", "/imagenes/comida/comidaKfc/pollo.jpg",8.99,"¡Saborea nuestras Alitas de Pollo BBQ! Jugosas y crujientes alitas de pollo bañadas en nuestra salsa barbacoa casera, con un equilibrio perfecto entre lo dulce y lo ahumado. Un festín de sabor en cada bocado que no querrás perderte. ¡Ordénalas ahora y disfruta de estas delicias para compartir o simplemente darte un capricho!");
        Comida bigMac = new Comida("Big mac", "/imagenes/comida/comidaMac/bigmac.png",10.50,"¡Prueba nuestra Hamburguesa Suprema! Carne 100% Angus, jugosa y sazonada, entre bollos artesanales con queso cheddar, tocino crujiente, lechuga fresca, tomate y nuestra irresistible salsa especial. Una explosión de sabores en cada bocado. ¡Ordénala ahora y disfruta de la perfección en cada mordisco!");
        Comida bigMacPollo = new Comida("Big Mac Pollo", "/imagenes/comida/comidaMac/bigmacpollo.png",12.00,"¡Sumérgete en nuestra Hamburguesa Grande de Pollo! Jugosa pechuga de pollo marinada en especias, asada a la parrilla para obtener un sabor perfectamente ahumado. Colocada entre dos bollos suaves, acompañada de crujiente lechuga, tomate fresco, y nuestra irresistible salsa especial.!");
        Comida burrito = new Comida("Burrito", "/imagenes/comida/comidaTaco/burrito.png",9.00,"¡Déjate llevar por nuestro Burrito Especial! Una tortilla suave rellena con tu elección de carne asada o pollo marinado, arroz sazonado, frijoles refritos, queso derretido y vegetales frescos. Todo envuelto en una combinación perfecta de sabores y texturas. ¡Ordénalo ahora y disfruta de este festín mexicano en cada mordisco!");
        Comida cocacola = new Comida("Cocacola Zero", "/imagenes/comida/comidaBk/cocacola.png",3.50,"Disfruta de la refrescante y clásica Coca-Cola Zero. Una bebida carbonatada con todo el sabor original de Coca-Cola, pero sin calorías. Una opción perfecta para saciar la sed sin preocuparte por el contenido calórico. ¡Acompaña tu comida con esta bebida refrescante y sin azúcar! ¡Pídela ahora y refréscate al instante!");
        Comida hamburKfc = new Comida("Hamburguesa", "/imagenes/comida/comidaKfc/hamburKfc.jpg",10.00,"¡Saborea nuestra Hamburguesa Clásica! Una jugosa y deliciosa carne de res entre dos suaves bollos, acompañada de queso derretido, lechuga fresca, rodajas de tomate y nuestra irresistible salsa. Un clásico que nunca pasa de moda. ¡Ordénala ahora y disfruta de la perfección en cada bocado!");
        Comida kebab1 = new Comida("Kebab Solo Pollo", "/imagenes/comida/comidaKebab/kebab1.jpg",7.50,"¡Prueba nuestro Kebab de Pollo Exquisito! Jugosas y tiernas tiras de pollo marinado, asadas a la perfección con especias tradicionales, envueltas en una suave tortilla de pan pita. Una explosión de sabores jugosos en cada mordisco. ¡Ordénalo ahora y déjate tentar por esta delicia!");
        Comida kebab2 = new Comida("Kebab Solo Carne", "/imagenes/comida/comidaKebab/kebab2.jpg",7.50,"¡Disfruta de nuestro Kebab de Carne Premium! Deliciosas y tiernas tiras de carne marinada, cuidadosamente asadas para obtener un sabor jugoso y lleno de aroma. Un clásico irresistible servido en una suave tortilla de pan pita. ¡Ordénalo ahora y saborea cada bocado lleno de sabor auténtico!");
        Comida mcFlurry = new Comida("Mc Flurry Kit-Kat", "/imagenes/comida/comidaMac/mcflurry.png",4.50,"¡Déjate tentar por nuestro delicioso helado tipo McFlurry con trozos crujientes de chocolate! Este postre cremoso y refrescante combina helado suave con pedazos de chocolate crujiente, todo mezclado a la perfección. Una explosión de sabor y texturas que te deleitará en cada cucharada. ¡Ordénalo ahora y disfruta de este capricho dulce y refrescante!");
        Comida menuSuper = new Comida("Menu Super KFC", "/imagenes/comida/comidaKfc/menuSuperkfc.jpg",12.50,"¡El Combo Supremo te espera! Nuestro menú incluye una deliciosa hamburguesa de carne de primera calidad, con una generosa porción de patatas fritas crujientes. Saborea cada bocado jugoso de la hamburguesa, acompañado por el irresistible sabor de las patatas fritas. ¡Ordénalo ahora y disfruta de esta combinación perfecta de sabor y satisfacción!");
        Comida muchosTacos = new Comida("Pack de 4 Tacos de Pollo", "/imagenes/comida/comidaTaco/muchosTacos.jpg",20.00,"¡Prueba nuestros Tacos Auténticos! Tortillas de maíz recién hechas, rellenas de tu elección de carne sazonada a la perfección, acompañada de cebolla picada, cilantro fresco, y una pizca de lima para resaltar los sabores. Una explosión de autenticidad en cada bocado. ¡Ordénalos ahora y disfruta de la verdadera experiencia de los sabores mexicanos!");
        Comida patatasKfc = new Comida("Patatas Fritas", "/imagenes/comida/comidaKfc/patatasKfc.jpg",5.50,"¡Nuestras Patatas Fritas Especiales te van a encantar! Cortadas en tiras finas y fritas al punto perfecto para obtener una textura crujiente por fuera y suave por dentro. Sazonadas con una mezcla secreta de especias que realzan su sabor único. El acompañamiento ideal para cualquier plato o simplemente como un delicioso snack. ¡Ordénalas ahora y descubre el auténtico placer de unas patatas fritas excepcionales!");
        Comida subway1= new Comida("Bocadillo Chicken Tikka", "/imagenes/comida/comidaSub/subway1.jpg",10.00,"¡Experimenta nuestro irresistible Bocadillo Chicken Tikka! Jugosas piezas de pollo marinado en especias tandoori, asadas a la perfección, y servidas en un pan recién horneado. Complementado con una mezcla fresca de lechuga crujiente, tomate maduro y una suave salsa de yogur y especias. Un festín de sabores indios en cada bocado. ¡Ordénalo ahora y disfruta de este viaje culinario a la India!");
        Comida bocadillo= new Comida("Bocadillo Albóndigas", "/imagenes/comida/comidaSub/subwayalbondigas.jpg",12.00,
                "¡Deléitate con nuestro Bocadillo de Albóndigas! Albóndigas caseras sazonadas con hierbas y especias, bañadas en una salsa de tomate casera y colocadas en un pan recién horneado. Cada mordisco es una explosión de sabores reconfortantes y deliciosos. ¡Ordénalo ahora y disfruta de este clásico favorito que te hará volver por más!");
        Comida bocadilloTomate = new Comida("Bocadillo con Tomate", "/imagenes/comida/comidaSub/subwaytomate.jpg",11.00,"¡Disfruta de nuestro Bocadillo Fresco con Tomate! Una combinación sencilla pero sabrosa de tomate maduro y fresco, cortado en rodajas perfectas, con un toque de sal y pimienta, todo envuelto en un pan recién horneado. Un clásico y refrescante bocado que realza el sabor natural del tomate. ¡Ordénalo ahora y saborea la frescura en cada mordisco!");
        Comida tacoPatatas = new Comida("Patatas Fritas", "/imagenes/comida/comidaTaco/tacoPatatas.jpg",5.00,"¡Descubre nuestras Patatas Fritas Especiales! Cortadas en trozos perfectamente crujientes por fuera y suaves por dentro. Sazonadas con una mezcla única de especias que resaltan su sabor característico. Estas patatas fritas son el complemento ideal para cualquier comida o un tentempié irresistible en cualquier momento del día. ¡Ordénalas ahora y déjate cautivar por su delicioso y distintivo sabor!");


        Restaurante mcDonalds = new Restaurante("mcdonalds",new ArrayList<Comida>(List.of(patatasFritas,bigMacPollo,bigMac,mcFlurry)), "/imagenes/restaurantesFoto/mcDonalds.jpg",10,45,"Mc Donalds Av. Madrid","/imagenes/restaurantesEnMenu/mc.jpg",new ArrayList<>(List.of("hamburguesa")));
        Restaurante bk = new Restaurante("burguerking",new ArrayList<Comida>(List.of(nuggets,cocacola,hamburguesa)), "/imagenes/restaurantesFoto/logoBK.jpg",20,30,"Burger King c/ Florida","/imagenes/restaurantesEnMenu/bk.jpg",new ArrayList<>(List.of("hamburguesa")));
        Restaurante kfc = new Restaurante("KFC",new ArrayList<Comida>(List.of(pollo,hamburKfc,menuSuper,patatasKfc)), "/imagenes/restaurantesFoto/kfc.jpg",25,50,"KFC Vialia Vigo","/imagenes/restaurantesEnMenu/kf.jpg",new ArrayList<>(List.of("hamburguesa","pollo")));
        Restaurante tacoBell = new Restaurante("Tacobell",new ArrayList<Comida>(List.of(taco,muchosTacos,tacoPatatas,burrito)), "/imagenes/restaurantesFoto/tacoBell.png",10,40, "Taco Bell Vialia Vigo","/imagenes/restaurantesEnMenu/taco.jpg",new ArrayList<>(List.of("taco")));
        Restaurante restauranteKebab = new Restaurante("RestauranteKebabs",new ArrayList<Comida>(List.of(kebab,kebab2,kebab1)), "/imagenes/restaurantesFoto/kebabRestaurante.jpg",35,50, "Las Palmas Torrecedeira Vigo","/imagenes/restaurantesEnMenu/kebab.jpg",new ArrayList<>(List.of("kebab")));
        Restaurante subway = new Restaurante("SUBWAY",new ArrayList<Comida>(List.of(bocadillos,subway1,bocadilloTomate,bocadillo)), "/imagenes/restaurantesFoto/subway.jpg",10,20,"Subway C.C. Gran Vía","/imagenes/restaurantesEnMenu/sub.jpg",new ArrayList<>(List.of("bocadillos")));
        this.listaRestaurantes = new ArrayList<>(List.of(mcDonalds,bk,kfc,tacoBell,restauranteKebab,subway));
    }
}
